### ISSUE TITLE
Update Frequency: how?

### ISSUE THREAD

**Issue by ryanchen26** [jwoglom/tconnectsync#12]
First of all, great work. I followed the posted direction, and it pulled 24hrs of data from Tconnect and displayed it on Nightscout. Awesome. However, the Android App only pushes data to Tconnect every hour, so how are you able to reduce that to 5 minutes?  I'd really like to try that someday.

Thanks, 
-Ryan

**Comment by jwoglom** [comment]
Hi Ryan,

Great question. I was able to modify the android app to push to tconnect every 5 minutes instead of every hour by decompiling the app. Check out https://github.com/jwoglom/tconnectpatcher to see the details.

Unfortunately, they made the app more difficult to decompile in more recent versions, such that if you decompile it, change a static variable that sets the update frequency to be lower, and then recompile the app notices that its signature changed and fails to run. So you need to find the APK for tconnect v1.2 and run it against the patcher.

There are also some moderately annoying side effects of this approach, such as every few days I need to wipe the data of the tconnect app because it gets in a bad state and won't upload anymore, then re-connect my pump over bluetooth and re-log in to get it working again. Because of this I haven't used the patched app in a few months and have just been dealing with the 1 hour data delay for now.

Hopefully, given enough time, it's possible for the community to build a fully third-party app that connects with the pump over bluetooth that lets it speak directly to nightscout and update more frequently (like what xDrip is to the official Dexcom app). I'd love to explore making something like this in the medium-term, but I haven't had the time to spearhead an initiative for it.

**Comment by ryanchen26** [comment]
Very impressive, but sorry to hear its not stable. I guess I'll hold off on trying. I made the Sentinel series of Fitbit clockfaces for monitoring multiple T1Ds (my 2 boys, both have TSlim X2 pumps). It would have been cool to see the pump basal and IOBs from the pump while their at school. That's why I'm interested. You know Tandem Diabetes has job openings in San Diego (some full time remote positions) that maybe someone like yourself could jump on. Just a thought. Either way, good stuff.
