### ISSUE TITLE
Possibility to sync blood sugar data as well?

### ISSUE THREAD

**Issue by JasonJShuler** [jwoglom/tconnectsync#16]
Hello! Thanks for this tool, its pretty awesome!

I was just wondering - Is it possible to also sync the blood sugar data, and calibrations?

I enter my calibrations on the pump, and they don't seem to show up in the Dexcom data - only t:connect.

If the data is available, could you point me in the right direction and I could try to do it myself?

Thanks!

**Comment by jwoglom** [comment]
Adding this functionality to be synchronized would definitely be possible, as BG data (CGM and manually-entered) is exposed via the API!

The tconnectws2 therapytimeline2csv endpoint returns blood sugar reading data from t:connect. The existing `WS2Api#therapy_timeline_csv()` method returns a `readingData` key which should contain a list of Python dicts containing the available BG data: https://github.com/jwoglom/tconnectsync/blob/master/tconnectsync/api/ws2.py#L63

IIRC, there is a field inside there that denotes whether the reading is from a manually entered BG (from the bolus screen) or CGM. If you're referring to G5/G6 calibrations I'm unsure where those go exactly, I suspect they'd be included here however (I have a G6 and don't need to calibrate).

We should add whether to upload BG data to Nightscout behind a flag, since many folks (myself included) already use xDrip to sync CGM data into Nightscout and/or already input manual BG/calibration data in xDrip or nightscout directly.

**Comment by jwoglom** [comment]
> Whenever Tandem fixes the constant t:connect logout issue on android... 

This is so irritating. And you can't even downgrade to an older version of the app to try and resolve it since login is broken on version < 1.5 🙃

Not sure how much hope I should put into their upcoming phone bolus implementation being good if they can't even get login sessions right...

**Comment by jwoglom** [comment]
Closing this issue since there is supported cgm and bolus synchronization in tconnectsync. Open a new issue if you experience problems.
