### ISSUE TITLE
feature request: include site change data

### ISSUE THREAD

**Issue by t1diotac** [jwoglom/tconnectsync#22]
Good afternoon!

Just some thoughts after using this for a bit. If it is possible, it would be nice to have other pump data included such as cartridge replacements, and fill cannula. With "fill cannula" a nice option would be have some sort of flag that allows that step to populate the site change log entry in NightScout, something like:
--site-change-when-fill-cannula
Ha, maybe that's a little wordy, just a thought though.

Battery level would be awesome too, I'm just not sure how much data is out there that can be pulled in from TConnect, so the "feature request" is just blind, more of a "wish list" I suppose.

Thanks!

**Comment by jwoglom** [comment]
Great ideas. I've created a structure of "synchronization features" which can be enabled or disabled by the user, which should allow us to iterate on adding in new data which can be synced to Nightscout without impacting existing users.

Cannula/cartridge data should definitely be possible -- I am hoping to work on this soon. I don't think battery is, at least as far as I know. Battery stats is trending more in the land of features which the community would likely need to build its own Android app that communicates with the pump with in order to extract -- e.g., we have xDrip which is an open-source implementation of the Dexcom android app (and in fact predates it!), this would be an open-source implementation of the Tandem app.

**Comment by t1diotac** [comment]
Very cool! I appreciate the work you've put into this, it has been very useful in the week or 2 that I've been using it so far!

**Comment by jwoglom** [comment]
@t1diotac Hot off the presses -- please take a look at the new PUMP_EVENTS feature!

It can detect the following types of pump events:
* Site/Cartridge Change (occurs for both a site change and a cartridge change)
* Empty Cartridge/Pump Shutdown (from my investigation, occurs either when the cartridge runs out of insulin OR you hard-shut off the pump)
* User Suspended (occurs when you manually disable insulin delivery)
* Exercise Mode
* Sleep Mode
* AutoBolus and CarbOnly events -- I'm not entirely sure what these do, but they exist as event types in tconnect


To try this out, update to the latest version of tconnectsync and enable PUMP_EVENTS using the `--features` flag. The feature options default to `--features BASAL BOLUS IOB`, so if you want to _add_ pump events to what is already being synchronized you would run with `--features BASAL BOLUS IOB PUMP_EVENTS`.

**Comment by rehudson** [comment]
@jwoglom : Great work on this!  I tried to use the PUMP_EVENTS feature but got an error:
tconnectsync: error: argument --features: invalid choice: 'PUMP_EVENTS' (choose from 'BASAL', 'BOLUS', 'IOB')

Is there something I need to do?  I'm running version 0.5.

Thanks so much!

**Comment by jwoglom** [comment]
@rehudson sounds like you just need to upgrade to the latest version which is 0.6

**Comment by t1diotac** [comment]
This works like a champ for me in the latest version! Very much appreciated!
