### ISSUE TITLE
docker image version does not match github release version

### ISSUE THREAD

**Issue by MatthewMazaika** [jwoglom/tconnectsync#94]
the version info in [setup.cfg](https://github.com/jwoglom/tconnectsync/blob/master/setup.cfg#L3) matches the latest dockerhub version [here](https://hub.docker.com/r/jwoglom/tconnectsync/tags) but the latest github release is [v0.9.5](https://github.com/jwoglom/tconnectsync/releases/tag/v0.9.5)

should we cut the github release first and then push that to dockerhub?

**Comment by jwoglom** [comment]
Thanks for noticing this. The GitHub releases right now are being manually created by me and I haven't bothered to create any recently since there have been no major changes. The versions past v0.9.5 were pushed to GitHub on the main branch and were also sent to pypi, but outside of one bugfix in v0.9.6 (https://github.com/jwoglom/tconnectsync/pull/92), there were no other major changes, just some added tests and CI fixes: https://github.com/jwoglom/tconnectsync/compare/v0.9.5...v0.9.8

Just to make this less confusing, I cut a new release now of the latest version and included a diff between it and the last GitHub-created release.
